// Combo-line content. The core line is the verified end-to-end play (same
// sequence as landing.turn, expanded with the resource logic per step).
// Card names & effects © Konami: reference only.
//
// To add a line: push an object to `lines`. Keep steps honest (verified card
// text only): unverified lines stay in `pending` until the effects are confirmed.
export default {
  intro:
    "Mitsurugi wins by looping tributes into searches and revivals. Below is the main line that turns a single starter into a board wipe plus a grind engine. Each step notes not just what to do, but why the resources come back.",

  lines: [
    {
      id: "main-1",
      name: "Standard full combo",
      section: "1 Card Combos",
      tag: "Bread and butter",
      starter: 'Any opener that reaches Habakiri: <a href="../cards/#preprep">Pre-Prep of Rites</a>, <a href="../cards/#prayers">Mitsurugi Prayers</a>, an <a href="../cards/#aramasa">Aramasa</a> Normal Summon, or <a href="../cards/#raggedrecords">Ragged Records of Rites</a>',
      result: "Habakiri, Murakumo, and Futsu no Mitama on board, plus a Rank 4 Xyz or Link 2 of your choice and a set Mitsurugi Great Purification",
      steps: [
        { n: "0", card: "Get to Habakiri", do: "Reach Habakiri through any opener: Pre-Prep of Rites, Mitsurugi Prayers, an Aramasa Normal Summon, or Ragged Records of Rites.",
          warn: "The next steps can vary a little depending on the rest of your hand and how you got to Habakiri." },
        { n: "1", card: "Habakiri effect in hand", do: "Reveal Habakiri, Special Summon Saji from the Deck, then tribute Saji.",
          warn: "Ash Blossom hits this trigger and stops the whole search. Bait it out first if you can. Though, most people would probably wait and hit Saji effect." },
        { n: "1.5", card: "Saji triggers in GY", do: "Add Mitsurugi Ritual to hand.",
          warn: "Droll & Lock Bird shuts off every further add for the turn once you make this search." },
        { n: "2", card: "Ritual summon from hand, tribute from Deck", do: "Activate Mitsurugi Ritual to Ritual Summon Habakiri, tributing Aramasa and Kusanagi from the Deck. If you run it, use NSS instead of Aramasa to revive it." },
        { n: "2.5", card: "Tributed monsters trigger", do: "CL1 Kusanagi returns Mitsurugi Ritual to hand; CL2 Aramasa fetches Futsu no Mitama.",
          why: "Both on-Tribute effects resolve from the GY. Taking the Ritual back sets up the second Ritual Summon in step 3. Doing Kusanagi's effect first allows you to chain block with Aramasa." },
        { n: "3", card: "Ritual summon from Deck, tribute from field", do: "Activate Mitsurugi Ritual again, tributing Habakiri to summon Ame no Murakumo from the Deck.",
          why: "Murakumo wipes the opponent's board on Special Summon." },
        { n: "3.5", card: "Habakiri on-Tribute", do: "Habakiri's on-Tribute effect adds Mitsurugi Mirror and revives itself." },
        { n: "4", card: "Mirror activation", do: "Activate Mitsurugi Mirror, tributing Murakumo to Special Summon Futsu no Mitama from the hand in defense position.",
          why: "Futsu is a 3400 DEF wall, a very big defender." },
        { n: "4.5", card: "Murakumo on-Tribute", do: "Murakumo activates in the GY, adding Mitsurugi Prayers and reviving itself." },
        { n: "5", card: "Prayers loop", do: "Activate Mitsurugi Prayers, tributing Futsu no Mitama to add Aramasa (pay 800 LP) and revive Saji from the GY.",
          why: "Prayers turns the spent Futsu into a fresh search plus a body." },
        { n: "5.5", card: "Mirror + Futsu trigger in GY", do: "As Prayers resolves, Futsu no Mitama and Mirror's GY effect triggers. Shuffle Mirror back into the deck, add Mitsurugi Great Purification and revive Futsu no Mitama.",
          why: "You get Futsu back and end on a live Trap." },
        { n: "6", card: "Flexible Extra Deck end", do: "Normal Summon the Aramasa you added, then overlay the two Level 4s (Saji and Aramasa) into any Rank 4 Xyz of your choice, or use them for a Link 2. Keep the Level 8 ritual monsters on board.",
          why: "The Level 8 bodies (Habakiri, Murakumo, the 3400 Futsu wall) are all strong on their own, so spend just the disposable Level 4s on the Extra Deck play." },
        { n: "6.5", card: "Set the Trap", do: "Set Mitsurugi Great Purification to finish, alongside any other cards that need to be set." },
      ],
    },
    {
      id: "main-2",
      name: "Aramasa Normal Summon line",
      section: "1 Card Combos",
      tag: "Aramasa opener",
      starter: 'An opener that starts with an <a href="../cards/#aramasa">Aramasa</a> Normal Summon.',
      result: "Habakiri, Murakumo, and Futsu no Mitama on board, plus a Rank 4 Xyz or Link 2 of your choice and a set Mitsurugi Great Purification",
      steps: [
        { n: "0", card: "Start on Aramasa", do: "Normal Summon Aramasa. Its effect adds Habakiri to hand.",
          why: "Aramasa's Normal-Summon search is the entry point." },
        { n: "1", card: "Habakiri effect in hand", do: "Reveal Habakiri, Special Summon Saji from the Deck, then tribute Aramasa (keep Saji on the field).",
          warn: "Ash Blossom hits this trigger and stops the whole search. Bait it out first if you can. Though, most people would probably wait and hit Saji effect." },
        { n: "1.5", card: "Saji triggers", do: "Add Mitsurugi Prayers to hand.",
          warn: "Droll & Lock Bird shuts off every further add for the turn once you make this search." },
        { n: "2", card: "Prayers loop", do: "Activate Mitsurugi Prayers, tributing Habakiri to add Ame no Murakumo (pay 800 LP) and revive Aramasa from the GY.",
          why: "Prayers turns the tributed Habakiri into a search plus a body, and leaves Habakiri in the GY to trigger next." },
        { n: "2.5", card: "Habakiri triggers in GY", do: "As Prayers hits the GY, Habakiri's GY effect triggers. Add Mitsurugi Ritual to hand. Unfortunately, we cannot revive Habakiri here as it was not properly summoned first." },
        { n: "3", card: "Ritual summon from hand, tribute from Deck", do: "Activate Mitsurugi Ritual to Ritual Summon Ame no Murakumo, tributing Kusanagi and Aramasa from the Deck.",
          why: "Murakumo wipes the opponent's board on Special Summon." },
        { n: "3.5", card: "Kusanagi triggers", do: "Kusanagi returns Mitsurugi Ritual to hand.",
          why: "Taking the Ritual back sets up the second Ritual Summon in step 4. Unfortunately, we cannot chain block Kusanagi here, as Aramasa's effect was already activated this turn." },
        { n: "4", card: "Ritual summon from Deck, tribute from field", do: "Activate Mitsurugi Ritual again, tributing Murakumo to Special Summon Futsu no Mitama from the Deck in defense position.",
          why: "Futsu is a 3400 DEF wall, a very big defender." },
        { n: "4.5", card: "Murakumo on-Tribute", do: "Murakumo activates in the GY, adding Mitsurugi Mirror and reviving itself." },
        { n: "5", card: "Mirror activation", do: "Activate Mitsurugi Mirror, tributing Futsu no Mitama to Special Summon Habakiri from the GY." },
        { n: "5.5", card: "Mirror + Futsu trigger in GY", do: "As Prayers resolves, Futsu no Mitama and Mirror's GY effect triggers. Shuffle Mirror back into the deck, add Mitsurugi Great Purification and revive Futsu no Mitama.",
          why: "You get the Futsu wall back and end on a live Trap." },
        { n: "6", card: "Flexible Extra Deck end", do: "Keep the Level 8 ritual monsters on board and overlay only the two Level 4s (Saji and Aramasa) into any Rank 4 Xyz of your choice, or use them for a Link 2.",
          why: "The Level 8 bodies (Habakiri, Murakumo, the 3400 Futsu wall) are already your board, so spend just the disposable Level 4s on the Extra Deck play." },
        { n: "6.5", card: "Set the Trap", do: "Set Mitsurugi Great Purification to finish, alongside any other cards that need to be set." },
      ],
    },
    {
      id: "main-3",
      name: "Prayers solo starter",
      section: "1 Card Combos",
      tag: "Prayers opener",
      starter: 'A lone <a href="../cards/#prayers">Mitsurugi Prayers</a>',
      result: "Habakiri, Murakumo, and Futsu no Mitama on board (three Level 8 bodies), plus a set Mitsurugi Great Purification, with an optional Link 2",
      steps: [
        { n: "0", card: "Open on Prayers", do: "Activate Mitsurugi Prayers to add Habakiri to hand.",
          why: "Prayers can reach Habakiri all by itself. The trade-off: spending it up front means you do NOT have the end-of-combo Prayers loop that Line 1 uses, so this line ends with fewer bodies." },
        { n: "1", card: "Habakiri effect in hand", do: "Reveal Habakiri, Special Summon Saji from the Deck, then tribute Saji.",
          warn: "Ash Blossom hits this trigger and stops the whole search. Bait it out first if you can. Though, most people would probably wait and hit Saji effect." },
        { n: "1.5", card: "Saji triggers in GY", do: "Add Mitsurugi Ritual to hand.",
          warn: "Droll & Lock Bird shuts off every further add for the turn once you make this search." },
        { n: "2", card: "Ritual summon from hand, tribute from Deck", do: "Activate Mitsurugi Ritual to Ritual Summon Habakiri, tributing Aramasa and Kusanagi from the Deck." },
        { n: "2.5", card: "Tributed monsters trigger", do: "CL1 Kusanagi returns Mitsurugi Ritual to hand; CL2 Aramasa fetches Futsu no Mitama.",
          why: "Both on-Tribute effects resolve from the GY. Taking the Ritual back sets up the second Ritual Summon in step 3." },
        { n: "3", card: "Ritual summon from Deck, tribute from field", do: "Activate Mitsurugi Ritual again, tributing Habakiri to summon Ame no Murakumo from the Deck.",
          why: "Murakumo wipes the opponent's board on Special Summon." },
        { n: "3.5", card: "Habakiri on-Tribute", do: "Habakiri's on-Tribute effect adds Mitsurugi Mirror and revives itself." },
        { n: "4", card: "Mirror activation", do: "Activate Mitsurugi Mirror, tributing Murakumo to Special Summon Futsu no Mitama from the hand in defense position.",
          why: "Futsu is a 3400 DEF wall, a very big defender." },
        { n: "4.5", card: "Murakumo on-Tribute", do: "Murakumo activates in the GY, adding Mitsurugi Great Purification and reviving itself." },
        { n: "5", card: "Extra Deck end", do: "Do not overlay into a Rank 8. Keep the three Level 8 monsters; if you need something from the extra deck, make a Link 2 off two of them.",
          why: "This line has no leftover Level 4's, so a Rank 4 isn't available. Prayers as your only starter pays off in three big Level 8 bodies instead of an Extra Deck piece." },
        { n: "5.5", card: "Set the Trap", do: "Set Mitsurugi Great Purification to finish, alongside any other cards that need to be set." },
      ],
    },
    {
      id: "main-4",
      name: "Pre-Preparation extended line",
      section: "1 Card Combos",
      tag: "Pre-Prep opener",
      starter: 'A lone <a href="../cards/#preprep">Pre-Preparation of Rites</a>. Make sure there is no Mitsurugi Mirror in your hand!',
      result: "Habakiri, Murakumo, and Futsu no Mitama on board, plus a Rank 4 Xyz or Link 2 of your choice, a set Mitsurugi Great Purification and Mitsurugi Prayers.",
      steps: [
        { n: "0", card: "Open on Pre-Prep", do: "Activate Pre-Preparation of Rites, adding Habakiri and Mitsurugi Mirror to hand.",
          why: "One card pre-loads both your Habakiri starter and the Mirror you need mid-combo, so this line ends a card richer than the others." },
        { n: "1", card: "Habakiri effect in hand", do: "Reveal Habakiri, Special Summon Saji from the Deck, then tribute Saji.",
          warn: "Ash Blossom hits this trigger and stops the whole search. Bait it out first if you can. Though, most people would probably wait and hit Saji effect." },
        { n: "1.5", card: "Saji triggers in GY", do: "Add Mitsurugi Ritual to hand.",
          warn: "Droll & Lock Bird shuts off every further add for the turn once you make this search." },
        { n: "2", card: "Ritual summon from hand, tribute from Deck", do: "Activate Mitsurugi Ritual to Ritual Summon Habakiri, tributing Aramasa and Kusanagi from the Deck." },
        { n: "2.5", card: "Tributed monsters trigger", do: "CL1 Kusanagi returns Mitsurugi Ritual to hand; CL2 Aramasa fetches Futsu no Mitama.",
          why: "Both on-Tribute effects resolve from the GY. Taking the Ritual back sets up the second Ritual Summon in step 3." },
        { n: "3", card: "Ritual summon from Deck, tribute from field", do: "Activate Mitsurugi Ritual again, tributing Habakiri to summon Ame no Murakumo from the Deck.",
          why: "Murakumo wipes the opponent's board on Special Summon." },
        { n: "3.5", card: "Habakiri on-Tribute", do: "Habakiri's on-Tribute effect adds Mitsurugi Prayers and revives itself." },
        { n: "4", card: "Mirror activation", do: "Activate the Mitsurugi Mirror you pre-searched, tributing Murakumo to Special Summon Futsu no Mitama from the hand in defense position.",
          why: "Futsu is a 3400 DEF wall, a very big defender." },
        { n: "4.5", card: "Murakumo on-Tribute", do: "Murakumo activates in the GY, adding Mitsurugi Great Purification and reviving itself." },
        { n: "5", card: "Prayers loop", do: "Activate Mitsurugi Prayers, tributing Futsu no Mitama to add Aramasa (pay 800 LP) and revive Kusanagi from the GY.",
          why: "Prayers turns the spent Futsu into a fresh search plus a Level 4 body." },
        { n: "5.5", card: "Mirror + Futsu trigger in GY", do: "As Prayers hits the GY, revive Futsu no Mitama; Futsu's GY effect adds a second Mitsurugi Prayers.",
          why: "You get the Futsu wall back and bank a spare Prayers to set as backup interaction." },
        { n: "6", card: "Flexible Extra Deck end", do: "Normal Summon the Aramasa you added, then overlay the two Level 4s (Kusanagi and Aramasa) into any Rank 4 Xyz of your choice, or use them for a Link 2. Keep the Level 8 ritual monsters on board.",
          why: "The Level 8 bodies (Habakiri, Murakumo, the 3400 Futsu wall) are already your board, so spend just the disposable Level 4s on the Extra Deck play." },
        { n: "6.5", card: "Set the Traps", do: "Set Mitsurugi Great Purification, and set the spare Prayers as extra interaction." },
      ],
    },
    {
      id: "two-card-placeholder",
      name: "Two-card combos",
      section: "2 Card Combos",
      placeholder: true,
      note: "Two-card extensions (double-starter lines and handtrap-proof routes) are being documented — check back soon.",
    },
  ],

  // Verified interactions worth knowing mid-combo (pulled from card tips).
  interactions: [
    { name: "Ash Blossom on the Mitsurugi Ritual Monsters", body:
      "Negating a Mitsurugi Ritual Monster's on-Tribute search also cancels its self-revive: both resolve as one effect. Bait or play around Ash before committing." },
    { name: "Mitsurugi Prayers, surprise wipe", body:
      "Set Prayers and activate on the opponent's turn to Special Summon Murakumo from hand or GY, dropping its board wipe like a Raigeki." },
    { name: "The negate is conditional", body:
      "Murakumo's discard-or-negate helps decks that WANT to discard (Dark World, Mermail). Respect the matchup instead of leaning on it." },
  ],

  // Lines awaiting verified effects before they go on the page.
  pending: ["Ogdoadic Rank 8 extension", "Fiendsmith omni-negate bridge"],
};
